name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build with Makefile
        run: |
          mingw32-make

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: shoot-em-up
          path: shoot-em-up.exe